### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [Rlopez91/colmaracademy#5]
Grade: **Meets Expectations**

Overall this project is working great! I really like how clean the HTML and CSS is to read over. You have everything very nicely sectioned so we can determine where everything needs to go. On top of this, you downloaded all of the images and stuck them in a local resource folder to allow for faster page loading. A couple things I would recommend is making sure you add alt tags to you images. I can see they are there but they are empty. We'll want to do this to make sure we provide a text descriptor for our images. Second, make sure you are using the correct closing tags or if an element is self closing, not using a closing tag. Next steps, I would try to make additional pages for this website with their own HTML and CSS.

Nice job!

**Comment by Rlopez91** [comment]
Thank you very much for your review and recommendations!
